# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Buum < Formula
  desc "Fast, multi-package manager updater CLI tool for macOS"
  homepage "https://github.com/EmreErinc/buum-cli"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/EmreErinc/buum-cli/releases/download/v0.1.3/buum-cli_0.1.3_darwin_amd64.tar.gz"
      sha256 "8eda3689cf5d6374725175d05fc4ff911a4f10197cec7c0887edb6fb0c3dbb3d"

      define_method(:install) do
        bin.install "buum"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/EmreErinc/buum-cli/releases/download/v0.1.3/buum-cli_0.1.3_darwin_arm64.tar.gz"
      sha256 "65074bd02671a260df3be4416c19627a04b2187074281e586b57779e2ead1a1e"

      define_method(:install) do
        bin.install "buum"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/EmreErinc/buum-cli/releases/download/v0.1.3/buum-cli_0.1.3_linux_amd64.tar.gz"
      sha256 "b6dc56e75256cb72d7603244d992424b6d86cdb0a14cfca41428f600fccfe32b"
      define_method(:install) do
        bin.install "buum"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/EmreErinc/buum-cli/releases/download/v0.1.3/buum-cli_0.1.3_linux_arm64.tar.gz"
      sha256 "81184dba311b391320db40ce4147a95a21a458c2460c999b9d028e9e0f127fb0"
      define_method(:install) do
        bin.install "buum"
      end
    end
  end

  test do
    system "#{bin}/buum --help"
  end
end
