# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Buum < Formula
  desc "Fast, multi-package manager updater CLI tool for macOS"
  homepage "https://github.com/EmreErinc/buum-cli"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/EmreErinc/buum-cli/releases/download/v0.1.2/buum-cli_0.1.2_darwin_amd64.tar.gz"
      sha256 "f6fa8241c8cdacc5015640bef1181e93b819656d62b27cf4afb02127712e576f"

      define_method(:install) do
        bin.install "buum"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/EmreErinc/buum-cli/releases/download/v0.1.2/buum-cli_0.1.2_darwin_arm64.tar.gz"
      sha256 "41c5019755e2ebbe46e6a32aa790ed6a87145c94e6003c789c0c674cd89d60e8"

      define_method(:install) do
        bin.install "buum"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/EmreErinc/buum-cli/releases/download/v0.1.2/buum-cli_0.1.2_linux_amd64.tar.gz"
      sha256 "47d294311266d64616a38778ab7cf0db8beb30ec0a62d9f9776cdf6c34955440"
      define_method(:install) do
        bin.install "buum"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/EmreErinc/buum-cli/releases/download/v0.1.2/buum-cli_0.1.2_linux_arm64.tar.gz"
      sha256 "c6de3097866879abbb95c1a1fd1b3f4d2f2bb01d806bad2b81c817593faac29d"
      define_method(:install) do
        bin.install "buum"
      end
    end
  end

  test do
    system "#{bin}/buum --help"
  end
end
